import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { cn } from '@/utils/classNames'

export const metadata: Metadata = {
  title: 'Motflix',
  description: 'Generated by Giang'
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased', geistSans.variable, geistMono.variable)}
      >
        {children}
      </body>
    </html>
  )
}
